name: Reusable workflow examplez
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  call-workflow-1-in-local-repo:
    uses: kawikao/python-test-1/.github/workflows/python-app.yml@main
