name: Reusable workflow example
on:
  push:
    branches: [ "main" ]
  workflow_call:

jobs:
  call-workflow-1-in-local-repo:
    uses: kawikao/python-test-1/.github/workflows/python-app.yml@main

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
